### ISSUE TITLE
i can't access http://localhost:9191/tenants/

### ISSUE THREAD

**Issue by muzma** [openMF/message-gateway#11]
I have started my tomcat  and tables in 'messagegateway' was created but when i try to access http://localhost:9191/tenants/ i didn't any respose(refused to connect).  anyone can tell me what configuration i miss?
![screen shot 2017-09-14 at 10 21 37 pm](https://user-images.githubusercontent.com/12964025/30438430-6aed6e5c-999b-11e7-8b84-88d0dabfe237.png)

**Comment by awasum** [comment]
Read the README on github and the following manual:

https://mifosforge.jira.com/wiki/spaces/docs/pages/166658049/Message+Gateway+Configuration

https://github.com/openMF/message-gateway

**Comment by francisguchie** [comment]
@muzma 

did you solve you problem? do you still need help?

**Comment by francisguchie** [comment]
you will have to add the following element in the server.xml

<Connector port="9191" protocol="HTTP/1.1" connectionTimeout="20000" useBodyEncodingForURI="true" redirectPort="8443" compression="on" compressableMimeType="text/html,text/xml,text/plain,text/css,application/json,application/javascript,application/x-javascript"/>

**Comment by Gomaa** [comment]
By the way, I had some problems with mysql configurations. Even the database script file, I had to do few modifications to it to make it work.

**Comment by francisguchie** [comment]
> By the way, I had some problems with mysql configurations. Even the database script file, I had to do few modifications to it to make it work.

For me it is not the case, 
everything works now but i had to create twillio account and i used the twillio option. 

i wish there was a way of making it hookable to other service providers

**Comment by francisguchie** [comment]
> you will have to add the following element in the server.xml

remove the commented lines when deploying / testing 

<Connector port="9191" protocol="HTTP/1.1" 
//This port is equal to the port configured in the properties file of the messagegetaway
connectionTimeout="20000" useBodyEncodingForURI="true" redirectPort="8443" 
//This port is equal to the port configured in your community app (mifosX)
compression="on" compressableMimeType="text/html,text/xml,text/plain,text/css,application/json,application/javascript,application/x-javascript"/>

**Comment by francisguchie** [comment]
@Gomaa 

i have done everything and managed to test the sms sending using the restAPI
but mifosX can not send messages
i keep getting this error

[nio-9191-exec-3] o.s.web.servlet.PageNotFound             : Request method 'POST' not supported

this is my arrangment
I am runing the gateway using     java -jar message-gateway-0.0.1.jar

but still it is not working

Even when i place the deployable war file inside mifosX webaps 

still i get the same message

**Comment by francisguchie** [comment]
I hope some one will comment

Exception in thread "SimpleAsyncTaskExecutor-473" retrofit.RetrofitError: 405 Method Not Allowed
        at retrofit.RetrofitError.httpError(RetrofitError.java:39)
        at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:382)
        at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
        at com.sun.proxy.$Proxy366.sendSmsBridgeConfigRequest(Unknown Source)
        at org.apache.fineract.infrastructure.hooks.processor.TwilioHookProcessor.sendRequest(TwilioHookProcessor.java:96)
        at org.apache.fineract.infrastructure.hooks.processor.TwilioHookProcessor.process(TwilioHookProcessor.java:72)
        at org.apache.fineract.infrastructure.hooks.listener.FineractHookListener.onApplicationEvent(FineractHookListener.java:75)
        at org.apache.fineract.infrastructure.hooks.listener.FineractHookListener.onApplicationEvent(FineractHookListener.java:36)
        at org.springframework.context.event.SimpleApplicationEventMulticaster$1.run(SimpleApplicationEventMulticaster.java:93)
        at java.lang.Thread.run(Thread.java:748)
